### ISSUE TITLE
关于英文单引号的格式

### ISSUE THREAD

**Issue by Miopas** [yeyouqun/GAWK-MT#2]
首先非常感谢这份工作，为我这样的 awk 初学者提供了很多便利。

在阅读第一章的时候 awk 脚本的单引号格式是这样的：
![image](https://user-images.githubusercontent.com/10841135/30577721-b168db64-9d42-11e7-8c2c-e6ea72621fbd.png)

正文中是否使用双引号或者不加引号更符合中文书写习惯？

**Comment by yeyouqun** [comment]
非常感觉你的建议。也许你是对的。当时我是考虑因为保持一致的中文标点，所以采用中文式的引号。另外，有用户建议我直接使用 texi 格式来进行翻译，这样类似的问题，就可以直接提交了。但是我确定没有更多的时间与精力来做这个转换工作，我希望有人能够做这样的工作。或者如果能够被接受到 gawk 源代码的 doc 中就更完美了。
